apiVersion: v2
name: schema-registry
version: 0.2.0
description: A Helm chart for Confluent Schema Registry on Kubernetes
type: application
keywords:
  - kafka
  - schema-registry
  - confluent
home: https://github.com/m4r1vs/helm-charts
sources:
  - https://github.com/m4r1vs/helm-charts
  - https://docs.confluent.io/platform/current/schema-registry/index.html
maintainers:
  - name: Ricardo Henriques
    email: ricardoaireshenriques@gmail.com
    url: https://github.com/m4r1vs
icon: https://assets.confluent.io/m/61d0fe7faad2f991/original/icon-schema-registry.svg
appVersion: 7.3.0
