apiVersion: v2
name: kstack
version: 0.2.4
description: A Helm chart for Confluent Platform on Kubernetes
type: application
keywords:
  - kafka
  - confluent
home: https://ricardo-aires.github.io/helm-charts/
sources:
  - https://github.com/ricardo-aires/helm-charts
  - https://kafka.apache.org/documentation/#configuration
  - https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html
dependencies:
  - name: kafka
    version: 0.2.1
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: kafka.enabled
    alias: kafka
  - name: schema-registry
    version: 0.2.0
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: schema-registry.enabled
    alias: schema-registry
  - name: kafka-connect
    version: 0.2.0
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: kafka-connect.enabled
    alias: kafka-connect
  - name: kafka-rest
    version: 0.2.0
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: kafka-rest.enabled
    alias: kafka-rest
  - name: ksqldb
    version: 0.2.3
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: ksqldb.enabled
    alias: ksqldb
  - name: kafdrop
    version: 0.2.0
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: kafdrop.enabled
    alias: kafdrop
maintainers:
  - name: Ricardo Henriques
    email: ricardoaireshenriques@gmail.com
    url: https://github.com/ricardo-aires
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/kafka.svg
appVersion: 7.3.0
