apiVersion: v2
name: kafka
version: 0.2.1
description: A Helm chart for Confluent Kafka on Kubernetes
type: application
keywords:
  - kafka
  - confluent
home: https://github.com/m4r1vs/helm-charts
sources:
  - https://github.com/m4r1vs/helm-charts
  - https://kafka.apache.org/documentation/#configuration
  - https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html
dependencies:
  - name: zookeeper
    version: 0.2.0
    repository: https://ricardo-aires.github.io/helm-charts/
    condition: zookeeper.enabled
    alias: zookeeper
maintainers:
  - name: Ricardo Henriques
    email: ricardoaireshenriques@gmail.com
    url: https://github.com/m4r1vs
icon: https://svn.apache.org/repos/asf/comdev/project-logos/originals/kafka.svg
appVersion: 7.3.0
